import {
  EmergencyTypeOption,
  HotspotZone,
  RescueProvider,
  VehicleProfile,
  EmergencyContact,
  TelemetryData,
  KenyaHotline,
  MedicalProfile,
} from '@/types/sos';

// Nairobi Expressway / Uhuru Highway Central Corridor
export const DEFAULT_USER_COORDS: [number, number] = [-1.2864, 36.8172];

export const KENYA_EMERGENCY_HOTLINES: KenyaHotline[] = [
  {
    name: 'National Police / Emergency Command',
    number: '999',
    category: 'Police',
    description: 'National central emergency response & flying squad dispatch.',
    tollFree: true,
    badge: 'NATIONAL 999',
  },
  {
    name: 'National GSM Emergency Relay',
    number: '112',
    category: 'Police',
    description: 'Universal mobile emergency channel across Safaricom & Airtel.',
    tollFree: true,
    badge: 'FREE 112',
  },
  {
    name: 'Kenya Red Cross Ambulance',
    number: '1199',
    category: 'Medical',
    description: '24/7 Paramedic ambulance dispatch and casualty evacuation.',
    tollFree: true,
    badge: 'RED CROSS 1199',
  },
  {
    name: 'AA Kenya Roadside Rescue',
    number: '+254 709 933 000',
    category: 'Road Rescue',
    description: 'Automobile Association of Kenya 24/7 certified heavy towing & winching.',
    tollFree: false,
    badge: 'AA KENYA',
  },
  {
    name: 'St John Ambulance Kenya',
    number: '+254 721 225 285',
    category: 'Medical',
    description: 'Emergency medical services, life support, and highway trauma care.',
    tollFree: false,
    badge: 'ST JOHN',
  },
  {
    name: 'NTSA Incident Hotline',
    number: '+254 709 932 000',
    category: 'Traffic',
    description: 'National Transport and Safety Authority highway clearance.',
    tollFree: false,
    badge: 'NTSA',
  },
];

export const EMERGENCY_CATEGORIES: EmergencyTypeOption[] = [
  {
    id: 'towing',
    label: 'Heavy Flatbed Towing',
    sublabel: 'Mechanical breakdown or transmission failure',
    iconName: 'Truck',
    estimatedArrivalMins: 11,
    coverageStatus: 'Covered (AA Kenya Relay)',
    requiresSpecialEquipment: true,
  },
  {
    id: 'accident',
    label: 'Road Accident & Collision',
    sublabel: 'Immediate clearance, police log & paramedic link',
    iconName: 'AlertTriangle',
    estimatedArrivalMins: 7,
    coverageStatus: 'Critical Priority Dispatch',
    requiresSpecialEquipment: true,
  },
  {
    id: 'flat_tire',
    label: 'Puncture & Tire Replacement',
    sublabel: 'Pothole blowout or rim replacement',
    iconName: 'Disc',
    estimatedArrivalMins: 9,
    coverageStatus: 'Covered (Instant Mobile Rig)',
  },
  {
    id: 'dead_battery',
    label: 'Battery Boost / Jumpstart',
    sublabel: '12V heavy duty boost or starter motor check',
    iconName: 'Zap',
    estimatedArrivalMins: 8,
    coverageStatus: 'Covered (On-Scene Van)',
  },
  {
    id: 'fuel_out',
    label: 'Emergency Fuel Delivery',
    sublabel: '10 Liters Unleaded / Low-Sulphur Diesel',
    iconName: 'Fuel',
    estimatedArrivalMins: 10,
    coverageStatus: 'Covered (Mobile Fuel Can)',
  },
  {
    id: 'stuck_winch',
    label: 'Mud / Escarpment Winch Pull',
    sublabel: 'Ditch recovery or rainy season mire',
    iconName: 'Anchor',
    estimatedArrivalMins: 14,
    coverageStatus: 'Covered (Heavy 4x4 Rig)',
    requiresSpecialEquipment: true,
  },
  {
    id: 'lockout',
    label: 'Key Lockout Assistance',
    sublabel: 'Automotive locksmith without window damage',
    iconName: 'Key',
    estimatedArrivalMins: 12,
    coverageStatus: 'Covered',
  },
];

export const MOCK_HOTSPOTS: HotspotZone[] = [
  {
    id: 'hs-1',
    name: 'A104 Kinungi Escarpment Blackspot',
    type: 'accident_cluster',
    severity: 'high',
    coordinates: [-0.7850, 36.5200],
    radiusMeters: 850,
    description: 'High-fatality winding descent along Naivasha corridor. Frequent heavy truck brake failure.',
    historicalIncidents: 94,
    recommendedPrecaution: 'Move car completely past the yellow ditch line. Switch on hazards immediately.',
  },
  {
    id: 'hs-2',
    name: 'A109 Mombasa Road - Salama Corridor',
    type: 'accident_cluster',
    severity: 'high',
    coordinates: [-1.8700, 37.2800],
    radiusMeters: 900,
    description: 'Fast container truck transit artery with sudden cattle crossings and unmarked gravel shoulders.',
    historicalIncidents: 81,
    recommendedPrecaution: 'Deploy red warning triangles 50 meters back. Do not stand in traffic lanes.',
  },
  {
    id: 'hs-3',
    name: 'A2 Thika Superhighway Juja Flyover',
    type: 'accident_cluster',
    severity: 'caution',
    coordinates: [-1.1020, 37.0140],
    radiusMeters: 600,
    description: 'High-speed multi-lane merge with pedestrian crossings and rapid sudden slowdowns.',
    historicalIncidents: 47,
    recommendedPrecaution: 'Exit onto the outer service road if vehicle can crawl safely.',
  },
  {
    id: 'hs-4',
    name: 'Southern Bypass Langata Forest Zone',
    type: 'low_signal_deadzone',
    severity: 'medium',
    coordinates: [-1.3320, 36.7550],
    radiusMeters: 750,
    description: 'Intermittent mobile cellular deadspot along National Park perimeter fence.',
    historicalIncidents: 23,
    recommendedPrecaution: 'App automatically buffers GPS coordinates over Safaricom emergency SMS channel.',
  },
  {
    id: 'hs-5',
    name: 'AA Kenya Central Response Hub (Hurlingham)',
    type: 'patrol_depot',
    severity: 'safe_haven',
    coordinates: [-1.2950, 36.7920],
    radiusMeters: 500,
    description: 'Automobile Association of Kenya 24/7 fast dispatch staging base with 6 heavy flatbeds.',
    historicalIncidents: 0,
    recommendedPrecaution: 'Rapid deployment hub guaranteeing 8–15 minute average arrival across Nairobi.',
  },
];

export const MOCK_PRIMARY_PROVIDER: RescueProvider = {
  id: 'prov-aa-01',
  companyName: 'AA Kenya Rapid Rescue (Unit 44)',
  driverName: 'Juma Omondi',
  driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  phoneMasked: '+254 709 933 000 [AA Kenya Line]',
  rating: 4.97,
  completedRescues: 1840,
  vehicleType: 'Isuzu FSR Heavy Hydraulic Flatbed',
  licensePlate: 'KDA 849X',
  currentCoordinates: [-1.2980, 36.8050],
  distanceMiles: 2.4,
  initialEtaMinutes: 9,
  currentEtaMinutes: 8,
  tier: 'Primary Responder',
  status: 'matched',
};

export const MOCK_BACKUP_PROVIDER: RescueProvider = {
  id: 'prov-redcross-02',
  companyName: 'Kenya Red Cross Emergency Recovery',
  driverName: 'Wanjiku Mwangi',
  driverAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  phoneMasked: '+254 700 395 395 [Red Cross Hotline]',
  rating: 4.99,
  completedRescues: 2450,
  vehicleType: 'Toyota LandCruiser 4x4 Winch & Rescue Rig',
  licensePlate: 'KDG 210M',
  currentCoordinates: [-1.2790, 36.8320],
  distanceMiles: 3.8,
  initialEtaMinutes: 12,
  currentEtaMinutes: 11,
  tier: 'Backup Heavy Rig',
  status: 'matched',
};

export const INITIAL_VEHICLES: VehicleProfile[] = [
  {
    id: 'veh-1',
    make: 'Toyota',
    model: 'Land Cruiser Prado TX',
    year: 2022,
    color: 'Pearl White',
    licensePlate: 'KDA 849X',
    vinLast4: '7192',
    type: 'SUV / 4WD',
    drivetrain: 'AWD / 4WD',
    isDefault: true,
    notes: 'Permanent 4WD. Full flatbed carry required for long towing.',
  },
  {
    id: 'veh-2',
    make: 'Subaru',
    model: 'Forester XT',
    year: 2021,
    color: 'Dark Metallic Grey',
    licensePlate: 'KDG 102Z',
    vinLast4: '4481',
    type: 'Saloon',
    drivetrain: 'AWD / 4WD',
    isDefault: false,
    notes: 'Low clearance sports bumper. Front winch attachment under bumper.',
  },
  {
    id: 'veh-3',
    make: 'Isuzu',
    model: 'D-Max Double Cab 4x4',
    year: 2023,
    color: 'Silver Grey',
    licensePlate: 'KCP 554T',
    vinLast4: '9920',
    type: 'Commercial Truck',
    drivetrain: 'Heavy Commercial',
    isDefault: false,
    notes: 'Fitted with heavy steel bullbar and high-lift jack points.',
  },
];

export const INITIAL_MEDICAL_PROFILE: MedicalProfile = {
  bloodType: 'O+',
  allergies: 'Penicillin, Shellfish',
  chronicConditions: 'Asthma (Inhaler in glovebox)',
  emergencyCareHospital: 'Aga Khan University Hospital / Nairobi Hospital',
  donorStatus: true,
  nhifShifNumber: 'SHIF-KE-8849201',
};

export const INITIAL_CONTACTS: EmergencyContact[] = [
  {
    id: 'cont-1',
    name: 'Grace Wambui (Next of Kin)',
    relationship: 'Next of Kin',
    phone: '+254 722 849 102',
    email: 'grace.w@gmail.com',
    notifyOnSos: true,
    alertChannel: 'SMS + Call',
    lastAlertStatus: 'Acknowledged',
  },
  {
    id: 'cont-2',
    name: 'David Kiprono (Fleet Ops)',
    relationship: 'Fleet Manager',
    phone: '+254 711 554 990',
    email: 'fleet@kenyatransit.co.ke',
    notifyOnSos: true,
    alertChannel: 'SMS',
    lastAlertStatus: 'Delivered',
  },
  {
    id: 'cont-3',
    name: 'Kenya Police Kinungi Command Post',
    relationship: 'Colleague',
    phone: '+254 700 999 112',
    notifyOnSos: false,
    alertChannel: 'SMS',
  },
];

export const INITIAL_TELEMETRY: TelemetryData = {
  latitude: -1.2864,
  longitude: 36.8172,
  accuracyMeters: 3.5,
  altitudeMeters: 1680,
  speedMph: 0,
  heading: '310° NW (Toward Westlands)',
  batteryLevel: 88,
  cellularSignal: 'Safaricom 4G/5G',
  weatherCondition: '24°C (75°F) / Overcast / Nairobi Expressway Corridor',
  timestamp: new Date().toISOString(),
  highwayMarker: 'A104 Nairobi-Nakuru Corridor @ Kinungi Escarpment Mile 72',
  nearestIntersection: 'Naivasha Flyover / Mai Mahiu Junction',
};
